name: Build and Publish to PyPI

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13", "3.14"]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          allow-prereleases: true

      - name: Install build dependencies
        run: pip install pybind11 build twine

      - name: Build wheel
        run: python -m build --wheel
        working-directory: StackTrace/src/python

      - name: Upload to PyPI directly
        run: twine upload StackTrace/src/python/dist/*.whl --skip-existing
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}